name: Build Ansible Execution Environment
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install Ansible Builder
      run: |
        python -m pip install --upgrade pip
        pip install ansible-builder
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/execution-environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-docker-
          
    - name: Build Ansible Execution Envinroment
      run: ansible-builder build --container-runtime docker
      
    # # Set up Docker (if not already installed)
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    # # Cache Docker layers to speed up builds
    # - name: Cache Docker layers
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.cache/docker
    #     key: ${{ runner.os }}-docker-${{ hashFiles('**/execution-environment.yml') }}
    #     restore-keys: |
    #       ${{ runner.os }}-docker-

    # # Build the Docker image
    # - name: Build Docker image
    #   run: |
    #     docker build -t my-ansible-ee -f Dockerfile .

    # # Optionally, login to DockerHub and push the image (if needed)
    # - name: Log in to Docker Hub
    #   if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # # Optionally, push to Docker Hub (or GitHub Container Registry)
    # - name: Push Docker image to Docker Hub
    #   if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
    #   run: |
    #     docker tag my-ansible-ee ${{ secrets.DOCKER_USERNAME }}/my-ansible-ee:latest
    #     docker push ${{ secrets.DOCKER_USERNAME }}/my-ansible-ee:latest

    # # Optionally, Push to GitHub Container Registry (GHCR)
    # - name: Push Docker image to GitHub Container Registry
    #   if: secrets.GHCR_USERNAME && secrets.GHCR_TOKEN
    #   run: |
    #     docker tag my-ansible-ee ghcr.io/${{ github.repository }}/my-ansible-ee:latest
<<<<<<< HEAD
    #     docker push ghcr.io/${{ github.repository }}/my-ansible-ee:latest
=======
    #     docker push ghcr.io/${{ github.repository }}/my-ansible-ee:latest
>>>>>>> 36cde97 (testing actions)
